### ISSUE TITLE
I Don't have the desired modules

### ISSUE THREAD

**Issue by ajaykaarthic** [arunponnusamy/cvlib#1]
![screenshot 53](https://user-images.githubusercontent.com/33996820/45495040-12992480-b790-11e8-9ab6-62bfdc7b6af0.png)

check out the picture for error.

Thanks in advance !

**Comment by arunponnusamy** [comment]
Hello @ajaykaarthic , I see that you are working on Windows. Apologies. I have not tested the library extensively on Windows. If possible try it on linux. If not, I will share a temporary solution to fix this issue on Windows. 

I have packaged the caffemodel and prototext file inside the python package, which are needed for applying face detection. The issue here is, on Windows, the library is searching for the file at a wrong location. As you can see the error message **Can't open C:\data\deploy.prototxt**. But the file is not there.

Now, a hack is, we can download the files manually and place it under `data` folder in `C` drive. Download [prototxt](https://s3.ap-south-1.amazonaws.com/arunponnusamy/pre-trained-weights/facedetection/deploy.prototxt) and [caffemodel](https://s3.ap-south-1.amazonaws.com/arunponnusamy/pre-trained-weights/facedetection/res10_300x300_ssd_iter_140000.caffemodel) file from the links and create a folder named`data` in `C` drive and put the files inside. Now it should work.

Well, this is a temporary hack. I will fix this issue in the next release. Let me know if this worked. Also checkout this [notebook](https://colab.research.google.com/drive/1N850w27QQHmJNMrZqtzsUpKWx33H0X--) on Google Colab.
 
Cheers.

**Comment by arunponnusamy** [comment]
Hello @ajaykaarthic , I have fixed the issue in the latest release. 
Get the latest version using `pip install --upgrade cvlib`
Now it should work fine. Let me know if you face any issues. Have fun with detecting faces. Cheers.

**Comment by arunponnusamy** [comment]
I am closing this issue. Feel free to reopen if the issue persists.

**Comment by ajaykaarthic** [comment]
Hey,
Sure ! I am sorry that i didn't respond.
